var annotated =
[
    [ "WindowType", "namespaceWindowType.htm", null ],
    [ "AccelerationEvent", "classAccelerationEvent.htm", "classAccelerationEvent" ],
    [ "AccelerometerEvent", "classAccelerometerEvent.htm", "classAccelerometerEvent" ],
    [ "AlsEvent", "classAlsEvent.htm", "classAlsEvent" ],
    [ "AngularVelocityEvent", "classAngularVelocityEvent.htm", "classAngularVelocityEvent" ],
    [ "ApplicationDescription", "classApplicationDescription.htm", "classApplicationDescription" ],
    [ "ApplicationDescriptionBase", "classApplicationDescriptionBase.htm", "classApplicationDescriptionBase" ],
    [ "AsyncCaller", "classAsyncCaller.htm", "classAsyncCaller" ],
    [ "AsyncCallerBase", "classAsyncCallerBase.htm", "classAsyncCallerBase" ],
    [ "BearingEvent", "classBearingEvent.htm", "classBearingEvent" ],
    [ "CLSError", "structCLSError.htm", "structCLSError" ],
    [ "CompassEvent", "classCompassEvent.htm", "classCompassEvent" ],
    [ "Details", "structDetails.htm", "structDetails" ],
    [ "Event", "classEvent.htm", "classEvent" ],
    [ "FlickGesture", "classFlickGesture.htm", "classFlickGesture" ],
    [ "FlickGestureRecognizer", "classFlickGestureRecognizer.htm", "classFlickGestureRecognizer" ],
    [ "FunctionWrapper", "classFunctionWrapper.htm", "classFunctionWrapper" ],
    [ "GestureStrip", "classGestureStrip.htm", "classGestureStrip" ],
    [ "GravityEvent", "classGravityEvent.htm", "classGravityEvent" ],
    [ "HostArm", "classHostArm.htm", "classHostArm" ],
    [ "HostArmBroadway", "classHostArmBroadway.htm", "classHostArmBroadway" ],
    [ "HostArmMantaray", "classHostArmMantaray.htm", "classHostArmMantaray" ],
    [ "HostArmOpal", "classHostArmOpal.htm", "classHostArmOpal" ],
    [ "HostArmQemu", "classHostArmQemu.htm", "classHostArmQemu" ],
    [ "HostArmQemuKeyFilter", "classHostArmQemuKeyFilter.htm", "classHostArmQemuKeyFilter" ],
    [ "HostArmTopaz", "classHostArmTopaz.htm", "classHostArmTopaz" ],
    [ "HostArmUnknown", "classHostArmUnknown.htm", "classHostArmUnknown" ],
    [ "HostArmWindsorNot", "classHostArmWindsorNot.htm", "classHostArmWindsorNot" ],
    [ "HostBase", "classHostBase.htm", "classHostBase" ],
    [ "HostInfo", "structHostInfo.htm", "structHostInfo" ],
    [ "HostQtDesktop", "classHostQtDesktop.htm", "classHostQtDesktop" ],
    [ "HostQtDesktopKeyFilter", "classHostQtDesktopKeyFilter.htm", "classHostQtDesktopKeyFilter" ],
    [ "HostQtDesktopMouseFilter", "classHostQtDesktopMouseFilter.htm", "classHostQtDesktopMouseFilter" ],
    [ "InputControl", "classInputControl.htm", "classInputControl" ],
    [ "InspectorWidget", "classInspectorWidget.htm", "classInspectorWidget" ],
    [ "JsonMessageParser", "classJsonMessageParser.htm", "classJsonMessageParser" ],
    [ "JsonValue", "classJsonValue.htm", "classJsonValue" ],
    [ "KeywordMap", "classKeywordMap.htm", "classKeywordMap" ],
    [ "LedControl", "classLedControl.htm", "classLedControl" ],
    [ "LinearAccelerationEvent", "classLinearAccelerationEvent.htm", "classLinearAccelerationEvent" ],
    [ "LocalePreferences", "classLocalePreferences.htm", "classLocalePreferences" ],
    [ "Localization", "classLocalization.htm", "classLocalization" ],
    [ "Location", "classLocation.htm", "classLocation" ],
    [ "LSError", "classLSError.htm", null ],
    [ "LSMessageJsonParser", "classLSMessageJsonParser.htm", "classLSMessageJsonParser" ],
    [ "MagneticFieldEvent", "classMagneticFieldEvent.htm", "classMagneticFieldEvent" ],
    [ "Mutex", "classMutex.htm", "classMutex" ],
    [ "MutexLocker", "classMutexLocker.htm", "classMutexLocker" ],
    [ "NYXAccelerationSensorConnector", "classNYXAccelerationSensorConnector.htm", "classNYXAccelerationSensorConnector" ],
    [ "NYXAlsSensorConnector", "classNYXAlsSensorConnector.htm", "classNYXAlsSensorConnector" ],
    [ "NYXAngularVelocitySensorConnector", "classNYXAngularVelocitySensorConnector.htm", "classNYXAngularVelocitySensorConnector" ],
    [ "NYXBearingSensorConnector", "classNYXBearingSensorConnector.htm", "classNYXBearingSensorConnector" ],
    [ "NYXConnectorBase", "classNYXConnectorBase.htm", "classNYXConnectorBase" ],
    [ "NYXConnectorObserver", "classNYXConnectorObserver.htm", "classNYXConnectorObserver" ],
    [ "NYXGravitySensorConnector", "classNYXGravitySensorConnector.htm", "classNYXGravitySensorConnector" ],
    [ "NyxInputControl", "classNyxInputControl.htm", "classNyxInputControl" ],
    [ "NYXJsonStringConst", "classNYXJsonStringConst.htm", null ],
    [ "NyxLedControl", "classNyxLedControl.htm", "classNyxLedControl" ],
    [ "NYXLinearAccelearationSensorConnector", "classNYXLinearAccelearationSensorConnector.htm", "classNYXLinearAccelearationSensorConnector" ],
    [ "NYXLogicalAccelerometerSensorConnector", "classNYXLogicalAccelerometerSensorConnector.htm", "classNYXLogicalAccelerometerSensorConnector" ],
    [ "NYXLogicalDeviceMotionSensorConnector", "classNYXLogicalDeviceMotionSensorConnector.htm", "classNYXLogicalDeviceMotionSensorConnector" ],
    [ "NYXLogicalDeviceOrientationSensorConnector", "classNYXLogicalDeviceOrientationSensorConnector.htm", "classNYXLogicalDeviceOrientationSensorConnector" ],
    [ "NYXLogicalOrientationSensorConnector", "classNYXLogicalOrientationSensorConnector.htm", "classNYXLogicalOrientationSensorConnector" ],
    [ "NYXLogicalSensorConnectorBase", "classNYXLogicalSensorConnectorBase.htm", "classNYXLogicalSensorConnectorBase" ],
    [ "NYXMagneticFieldSensorConnector", "classNYXMagneticFieldSensorConnector.htm", "classNYXMagneticFieldSensorConnector" ],
    [ "NYXOrientationSensorConnector", "classNYXOrientationSensorConnector.htm", "classNYXOrientationSensorConnector" ],
    [ "NYXRotationSensorConnector", "classNYXRotationSensorConnector.htm", "classNYXRotationSensorConnector" ],
    [ "NYXScreenProximitySensorConnector", "classNYXScreenProximitySensorConnector.htm", "classNYXScreenProximitySensorConnector" ],
    [ "NYXShakeSensorConnector", "classNYXShakeSensorConnector.htm", "classNYXShakeSensorConnector" ],
    [ "OrientationEvent", "classOrientationEvent.htm", "classOrientationEvent" ],
    [ "ProcessKiller", "classProcessKiller.htm", "classProcessKiller" ],
    [ "ProximityEvent", "classProximityEvent.htm", "classProximityEvent" ],
    [ "QEvent", "classQEvent.htm", null ],
    [ "QGesture", "classQGesture.htm", null ],
    [ "QGestureRecognizer", "classQGestureRecognizer.htm", null ],
    [ "QObject", "classQObject.htm", null ],
    [ "QWidget", "classQWidget.htm", null ],
    [ "RefCounted", "classRefCounted.htm", "classRefCounted" ],
    [ "RotationEvent", "classRotationEvent.htm", "classRotationEvent" ],
    [ "Sender", "classSender.htm", "classSender" ],
    [ "SensorNames", "classSensorNames.htm", null ],
    [ "Settings", "classSettings.htm", "classSettings" ],
    [ "ShakeEvent", "classShakeEvent.htm", "classShakeEvent" ],
    [ "Signal", "classSignal.htm", "classSignal" ],
    [ "Signal< Arg0, Arg1, Arg2, Arg3, void >", "classSignal_3_01Arg0_00_01Arg1_00_01Arg2_00_01Arg3_00_01void_01_4.htm", "classSignal_3_01Arg0_00_01Arg1_00_01Arg2_00_01Arg3_00_01void_01_4" ],
    [ "Signal< Arg0, Arg1, Arg2, void, void >", "classSignal_3_01Arg0_00_01Arg1_00_01Arg2_00_01void_00_01void_01_4.htm", "classSignal_3_01Arg0_00_01Arg1_00_01Arg2_00_01void_00_01void_01_4" ],
    [ "Signal< Arg0, Arg1, void, void, void >", "classSignal_3_01Arg0_00_01Arg1_00_01void_00_01void_00_01void_01_4.htm", "classSignal_3_01Arg0_00_01Arg1_00_01void_00_01void_00_01void_01_4" ],
    [ "Signal< Arg0, void, void, void, void >", "classSignal_3_01Arg0_00_01void_00_01void_00_01void_00_01void_01_4.htm", "classSignal_3_01Arg0_00_01void_00_01void_00_01void_00_01void_01_4" ],
    [ "Signal< void, void, void, void, void >", "classSignal_3_01void_00_01void_00_01void_00_01void_00_01void_01_4.htm", "classSignal_3_01void_00_01void_00_01void_00_01void_00_01void_01_4" ],
    [ "SignalBase", "classSignalBase.htm", "classSignalBase" ],
    [ "SingletonTimer", "classSingletonTimer.htm", "classSingletonTimer" ],
    [ "Slot", "classSlot.htm", "classSlot" ],
    [ "Slot< Receiver, Arg0, Arg1, Arg2, Arg3, void >", "classSlot_3_01Receiver_00_01Arg0_00_01Arg1_00_01Arg2_00_01Arg3_00_01void_01_4.htm", "classSlot_3_01Receiver_00_01Arg0_00_01Arg1_00_01Arg2_00_01Arg3_00_01void_01_4" ],
    [ "Slot< Receiver, Arg0, Arg1, Arg2, void, void >", "classSlot_3_01Receiver_00_01Arg0_00_01Arg1_00_01Arg2_00_01void_00_01void_01_4.htm", "classSlot_3_01Receiver_00_01Arg0_00_01Arg1_00_01Arg2_00_01void_00_01void_01_4" ],
    [ "Slot< Receiver, Arg0, Arg1, void, void, void >", "classSlot_3_01Receiver_00_01Arg0_00_01Arg1_00_01void_00_01void_00_01void_01_4.htm", "classSlot_3_01Receiver_00_01Arg0_00_01Arg1_00_01void_00_01void_00_01void_01_4" ],
    [ "Slot< Receiver, Arg0, void, void, void, void >", "classSlot_3_01Receiver_00_01Arg0_00_01void_00_01void_00_01void_00_01void_01_4.htm", "classSlot_3_01Receiver_00_01Arg0_00_01void_00_01void_00_01void_00_01void_01_4" ],
    [ "Slot< Receiver, void, void, void, void, void >", "classSlot_3_01Receiver_00_01void_00_01void_00_01void_00_01void_00_01void_01_4.htm", "classSlot_3_01Receiver_00_01void_00_01void_00_01void_00_01void_00_01void_01_4" ],
    [ "SlotBase", "classSlotBase.htm", "classSlotBase" ],
    [ "SlotBase< Arg0, Arg1, Arg2, Arg3, void >", "classSlotBase_3_01Arg0_00_01Arg1_00_01Arg2_00_01Arg3_00_01void_01_4.htm", "classSlotBase_3_01Arg0_00_01Arg1_00_01Arg2_00_01Arg3_00_01void_01_4" ],
    [ "SlotBase< Arg0, Arg1, Arg2, void, void >", "classSlotBase_3_01Arg0_00_01Arg1_00_01Arg2_00_01void_00_01void_01_4.htm", "classSlotBase_3_01Arg0_00_01Arg1_00_01Arg2_00_01void_00_01void_01_4" ],
    [ "SlotBase< Arg0, Arg1, void, void, void >", "classSlotBase_3_01Arg0_00_01Arg1_00_01void_00_01void_00_01void_01_4.htm", "classSlotBase_3_01Arg0_00_01Arg1_00_01void_00_01void_00_01void_01_4" ],
    [ "SlotBase< Arg0, void, void, void, void >", "classSlotBase_3_01Arg0_00_01void_00_01void_00_01void_00_01void_01_4.htm", "classSlotBase_3_01Arg0_00_01void_00_01void_00_01void_00_01void_01_4" ],
    [ "SlotBase< void, void, void, void, void >", "classSlotBase_3_01void_00_01void_00_01void_00_01void_00_01void_01_4.htm", "classSlotBase_3_01void_00_01void_00_01void_00_01void_00_01void_01_4" ],
    [ "sptr", "classsptr.htm", "classsptr" ],
    [ "SyncTask", "classSyncTask.htm", "classSyncTask" ],
    [ "SysMgrEvent", "classSysMgrEvent.htm", null ],
    [ "TaskBase", "classTaskBase.htm", "classTaskBase" ],
    [ "Time", "classTime.htm", null ],
    [ "Timer", "classTimer.htm", "classTimer" ],
    [ "TimerBase", "classTimerBase.htm", "classTimerBase" ],
    [ "TimerHandle", "structTimerHandle.htm", "structTimerHandle" ],
    [ "TimerSource", "structTimerSource.htm", "structTimerSource" ],
    [ "Trackable", "classTrackable.htm", "classTrackable" ],
    [ "WindowProperties", "structWindowProperties.htm", "structWindowProperties" ]
];